In [1]:
import numpy as np

1. Initialize a 2D array $M5×10$ with value 7.

In [2]:
M = np.empty([5,10])

for i in range(5):
    for j in range(10):
        M[i,j] = 7
M

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [3]:
M = np.full([5,10],7)
M

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [4]:
M = np.ones([5,10]) * 7
M

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

2. Vectorize the following code

In [5]:
rows, cols = 3, 4
data = np.random.randint(10, size=(rows, cols))

In [6]:
for i in range(rows):
    for j in range(cols):
        if data[i][j] > 0:
            data[i][j] = 0
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
data[data > 0] = 0
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

3. Reverse an array

In [8]:
a = np.arange(10)
b = a[::-1]
c = np.flipud(a)
print(b,c)

[9 8 7 6 5 4 3 2 1 0] [9 8 7 6 5 4 3 2 1 0]


4. Obtain the mean of each column of a 2D array $x$. Ignore elements that are less than or equal to 0.

In [9]:
a = np.array([[2, 4, 5], [-3, 8, -7], [0, 6, 4.0], [0, 3, 4]])
mask = a > 0

print(a)
print(mask)

col_sums = np.sum(a * mask, axis=1)
counts = np.sum(mask, axis=1)

print(a * mask)

means = col_sums / counts
print(means)


[[ 2.  4.  5.]
 [-3.  8. -7.]
 [ 0.  6.  4.]
 [ 0.  3.  4.]]
[[ True  True  True]
 [False  True False]
 [False  True  True]
 [False  True  True]]
[[ 2.  4.  5.]
 [-0.  8. -0.]
 [ 0.  6.  4.]
 [ 0.  3.  4.]]
[3.66666667 8.         5.         3.5       ]


5. Remove from a vector all the elements that are equal to the biggest element.

In [10]:
x = np.array([6, 0, 0, 3, 2, 5, 6])
x_max = x.max()

indexs = np.where(x == x_max)
np.delete(x, indexs)


array([0, 0, 3, 2, 5])

6. A vector $x$ contains some 0s. Create $y$ such that $y[i]$ is 0 if $x[i]$ is 0, otherwise $y[i]$ is $log(x[i])$.

In [11]:
x = np.array([0, 2, 3, -4, 2, 1, 3, -1, -2])
indexs = x > 0

y = np.zeros(len(x))

print(indexs)

y[indexs] = np.log(x[indexs])
print(y)


[False  True  True False  True  True  True False False]
[0.         0.69314718 1.09861229 0.         0.69314718 0.
 1.09861229 0.         0.        ]


7. Calculate the sum of the elements along the main diagonal of a square matrix M.

In [12]:
def diagonal_sum(M):
    sum = 0
    for i in range(len(M)):
        sum += M[i,i]
    return sum

M = np.array([[1,2,3],[2,2,2],[3,2,1]])

print(diagonal_sum(M))
print(M.trace())


4
4


8. Check if a matrix M is a lower, upper or diagonal triangular matrix.

In [13]:
M = np.array([[1,0,0],[0,1,0],[0,0,1]])

# check if lower triangular matrix
res1 = np.allclose(M, np.tril(M))
print(res1)

# check if upper triangular matrix
res2 = np.allclose(M, np.triu(M))
print(res2)

# check if diagonal triangular matrix
res3 = np.allclose(M, np.diag(np.diag(M)))
print(res3)

True
True
True


9. Vectorize the following code

In [14]:
def threshold_python(M, max_value, min_value):
    n = M.shape[0]
    m = M.shape[1]
    for i in range(n):
        for j in range(m):
            c = M[i][j]
            if c > max_value:
                M[i][j] = max_value
            elif c < min_value:
                M[i][j] = min_value
    return M


def threshold_vector(M, max_value, min_value):
    M[M > max_value] = max_value
    M[M < min_value] = min_value
    return M


In [15]:
M = np.array([[1, 0, 0, 2, 4], [3, 2, 4, 6, 3]])
tp1 = threshold_python(M, 4, 2)
tp2 = threshold_vector(M, 4, 2)

print(tp1)
print(tp2)


[[2 2 2 2 4]
 [3 2 4 4 3]]
[[2 2 2 2 4]
 [3 2 4 4 3]]


10. Vectorize the following code

In [16]:
x = np.linspace(-2., 2., 5)
y = np.zeros(x.shape)

for i in range(len(x)):
    if x[i] <= 0.5:
        y[i] = x[i]**2
    else:
        y[i] = -x[i]

print(x)
print(y)

[-2. -1.  0.  1.  2.]
[ 4.  1.  0. -1. -2.]


In [17]:
x = np.linspace(-2., 2., 5)
y = np.where(x <= 0.5, x**2, -x)

print(x)
print(y)

[-2. -1.  0.  1.  2.]
[ 4.  1.  0. -1. -2.]


11. Computation of $sin(x)$.

In [18]:
n = 10000000
x = np.linspace(0, 1, n+1)

In [19]:
# Non-vectorized version:
def sin_func(x):
    res = np.zeros_like(x)
    for i in range(len(x)):
        res[i] = np.sin(x[i])
    return res

y = sin_func(x)
print(y)

[0.00000000e+00 1.00000000e-07 2.00000000e-07 ... 8.41470877e-01
 8.41470931e-01 8.41470985e-01]


In [20]:
# Vectorized version:
y = np.sin(x)
print(y)

[0.00000000e+00 1.00000000e-07 2.00000000e-07 ... 8.41470877e-01
 8.41470931e-01 8.41470985e-01]


12. Problem: sum up two lists of integers.

In [21]:
def add_python(Z1, Z2):
    return [z1+z2 for (z1, z2) in zip(Z1, Z2)]


def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)


In [22]:
Z1 = [[1,2],[3,4]]
Z2 = [[5,6],[7,8]]

Z3 = Z1 + Z2
Z4 = add_python(Z1, Z2)
Z5 = add_numpy(Z1, Z2)

print(Z3)
print(Z4)
print(Z5)

[[1, 2], [3, 4], [5, 6], [7, 8]]
[[1, 2, 5, 6], [3, 4, 7, 8]]
[[ 6  8]
 [10 12]]
