In [1]:
import cv2 as cv
import numpy as np

In [2]:
A = np.array([
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
], dtype='uint8')


In [3]:
B = cv.resize(A.astype('float32'), dsize=(12, 12)).astype('uint8')


In [4]:
print(A)
print(B)

[[0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [5]:
def rotate(image, angle, center = None, scale = 1.0):
    (h, w) = image.shape[:2]

    if center is None:
        center = (w / 2, h / 2)

    # Perform the rotation
    M = cv.getRotationMatrix2D(center, angle, scale)
    rotated = cv.warpAffine(image, M, (w, h))

    return rotated

In [6]:
C = rotate(A, 45)


In [7]:
print(A)
print(C)

[[0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 1 1 1 0 0 0]
 [0 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [8]:
def translation(image, x, y):
    T = np.float32([[1, 0, x], [0, 1, y]])
    return cv.warpAffine(image, T, image.shape)


In [9]:
D = translation(A, 0, 2)


In [10]:
print(A)
print(D)

[[0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]]


In [11]:
img = np.array([
    [21, 21, 21, 95, 169, 243, 243, 243],
    [21, 21, 21, 95, 169, 243, 243, 243],
    [21, 21, 21, 95, 169, 243, 243, 243],
    [21, 21, 21, 95, 169, 243, 243, 243],
])


In [12]:
n = img.size
pi = np.array([12/n, 4/n, 4/n, 12/n])


In [13]:
E = -np.sum(pi * np.log2(pi))
E

1.811278124459133